server:
  port: 8090

spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes: #网关路由配置
        - id: server-a
          uri: lb://server-a
          predicates: #路由断言设置路由规则
            - Path=/server-a/**


sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: Authorization
  # jwt秘钥
  jwt-secret-key: lin
  # token前缀
  token-prefix: Bearer
  is-read-cookie: false



