server:
  port: 8091

spring:
  application:
    name: server-a
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        cluster-name: CD
    openfeign:
      client:
        config:
          default:
            loggerLevel: full
      httpclient:
        hc5:
          enabled: true
    loadbalancer:
      nacos:
        enabled: true #使用nacos负载均衡策略